version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    labels:
      - dependencies
    versioning-strategy: widen
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "eslint-scope"
          - "json-parse-even-better-errors"
          - "strip-ansi"
          - "rimraf"
          - "mime-types"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    labels:
      - dependencies
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    labels:
      - dependencies
    groups:
      dependencies:
        patterns:
          - "*"
