name: Dependabot

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.repository == 'webpack/webpack'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: lts/*
          cache: yarn

      - name: Dedupe yarn
        run: |
          yarn --frozen-lockfile
          yarn fix:yarn

      - name: Commit changes
        run: |
          git config --local user.name "dependabot[bot]"
          git config --local user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git add .
          if ! git diff --quiet --exit-code || ! git diff --staged --quiet --exit-code; then
            git commit -m "chore: dedupe yarn"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No changes to commit"
          fi

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'
        run: |
          gh pr checkout "$PR_URL"

          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_URL"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi

          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
